controller_manager:
  ros__parameters:
    update_rate: 100

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_pitch_joint
      - wrist_roll_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: true

    constraints:
      stopped_velocity_tolerance: 0.5
      goal_time: 5.0

gripper_controller:
  ros__parameters:
    joints:
      - gripper_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: true

    constraints:
      stopped_velocity_tolerance: 0.5
      goal_time: 2.0
      gripper_joint:
        goal: 0.1